// Generated by CoffeeScript 1.9.0
(function() {
  var changeNumbers, inner, outer;

  outer = 4;

  changeNumbers = function() {
    var inner;
    inner = -1;
    return outer = 10;
  };

  inner = changeNumbers();

  console.log(inner);

}).call(this);
